In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cpu


## Introduction to tensor
### Creating tensors

PyTorch tensors are created using `torch.Tensor()` ([tensor docs](https://pytorch.org/docs/stable/tensors.html))

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,1])
vector

tensor([7, 1])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX 
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]],
                       [[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([2, 3, 3])

In [25]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensor

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.  
`random numbers -> look at data -> update numbers -> look at data -> update numbers`

`torch.rand()` ([random tensor docs](https://pytorch.org/docs/stable/generated/torch.rand.html))

In [26]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8216, 0.8883, 0.4668, 0.3687],
        [0.8506, 0.8355, 0.5573, 0.9300],
        [0.7806, 0.5997, 0.6158, 0.0965]])

In [27]:
random_tensor.ndim

2

In [28]:
# Create a random image with similar shape to an image tensor
rand_image_tensor = torch.rand(224,224,3)
rand_image_tensor.ndim, rand_image_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zero and Ones Tensors

In [35]:
zeros = torch.zeros(1,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [34]:
ones = torch.ones(2,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [39]:
# Use torch.range()
one_to_ten = torch.arange(1,11)

In [40]:
torch.arange(0,1050,50)

tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000])

In [42]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [47]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float 16)
                               device=None, # what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [49]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
`tensor.dtype`  
`tensor.shape`  
`tensor.device`  

In [50]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5609, 0.3350, 0.8749, 0.8459],
        [0.1361, 0.6437, 0.9666, 0.2899],
        [0.8031, 0.7920, 0.0938, 0.6484]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (operations)

- addition
- subtraction
- multiplication (element-wise)
- division
- matrix multiplication

In [51]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [53]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [54]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [55]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [56]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix Multiplication
You can also use `torch.mm()` which is a short for `torch.matmul()`  
 1. The inner dimension must match.
 - (3, 2) @ (3, 2) won't work
 - (2, 3) @ (3, 2) will work
 2. The resulting matrix has the shape of the outer dimensions.
 - (3, 2) @ (2, 3) -> (3, 3)

In [57]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [59]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.82 ms, sys: 0 ns, total: 2.82 ms
Wall time: 9.88 ms


tensor(14)

In [60]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 58 µs, sys: 0 ns, total: 58 µs
Wall time: 59.6 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [61]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [62]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [63]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (aggregation)

In [65]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [68]:
# You can also do the same as above with torch methods.
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [69]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Reshaping stacking squeezing and unsqueezing
   
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible) can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`) all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

In [71]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [72]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [73]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))